//userfly.com
(function(){var JSON={stringify:Object.toJSON};var __userfly_crawl_url='http://asset.userfly.com/users/2388/crawl.jpg?url=';var __userfly_capture_url='http://asset.userfly.com/users/2388/capture.jpg?data=';var debug=function(a){jQuery("#debug").append(a+"\n")};var object2buffer=function(a,b,c,d){var f="";var g="";b=b||1;c=c||0;d=d||"";if(c>=b){return""}
try{for(var h in a){var i;try{i=typeof(a[h])}
catch(e){continue}
if(i=="function"){continue}
if(i=="object"){if(g=object2buffer(a[h],b,c+1,d+"\t")){f+=d+h+":\n"+g}}
else{f+=d+h+": "+a[h]+"\n"}}}
catch(e){return""}
return f};var object2hash=function(a,b,c){var d={};var f={};b=b||1;c=c||0;if(c>=b){return null}
try{for(var g in a){var h;try{h=typeof(a[g])}
catch(e){continue}
if(h=="function"){continue}
if(h=="object"){if(f=object2hash(a[g],b,c+1)){d[g]=f}}
else if(typeof(a[g])!="string"||a[g].length>0){d[g]=a[g]}}}
catch(e){return null}
return d};var compress=function(s){return s};var encrypt=function(s){var e="";for(var i=0,j=s.length;i<j;i++){e+=String.fromCharCode(s.charCodeAt(i)+1)}
return e};if(typeof(__userfly_crawl_url)!="undefined"){(function(a){var i=new Image();i.src=a+compress(encodeURIComponent(encrypt(document.location.href)))+'&c='+compress(encodeURIComponent(encrypt(document.cookie)))+'&n='+compress(encodeURIComponent(encrypt(JSON.stringify(object2hash(navigator)))))+'&s='+compress(encodeURIComponent(encrypt(JSON.stringify(object2hash(screen)))));i.onload=i.onerror=function(){i.onload=null;i.onerror=null}}
(__userfly_crawl_url))}
var EVENT_MOUSEMOVE=0;var EVENT_MOUSEDOWN=1;var EVENT_MOUSEUP=2;var EVENT_CLICK=3;var EVENT_KEYPRESS=4;var EVENT_SCROLL=5;var EVENT_RESIZE=6;var EVENT_FOCUS=7;var EVENT_SUBMIT=8;var EVENT_CHANGE=9;var EVENT_BLUR=10;var EVENT_KEYUP=11;var EVENT_BUFFER=100;var URI_LENGTH=2083;function CaptureRequest(g,h,j,k,l){this.url=g;this.timestamp=h;this.events=j;this.details=k;this.times=l;this.send=function(){var a={timestamp:this.timestamp,events:this.events,details:this.details,times:this.times};var b=this.url+compress(encodeURIComponent(encrypt(JSON.stringify(a))));if(b.length>URI_LENGTH){if(this.events.length<=1){}
else{var c=(this.events.length/2)|0;var d=new CaptureRequest(this.url,this.timestamp,this.events.slice(0,c),this.details.slice(0,c),this.times.slice(0,c));var e=d.times[d.times.length-1];d.send();var f=new CaptureRequest(this.url,this.timestamp+e,this.events.slice(c),this.details.slice(c),this.times.slice(c));for(var i=0;i<f.times.length;i++){f.times[i]-=e}
f.send()}}
else{var i=new Image();i.src=b;i.onload=i.onerror=function(){i.onload=null;i.onerror=null}}}}
var capture={events:[],details:[],times:[],total:0,timestamp:new Date().getTime(),prefix:"userfly",separator:"_",index:0,url:"",callbacks:[function(e){capture._addEvent(EVENT_MOUSEMOVE,{x:e.pageX,y:e.pageY})},function(e){capture._addEvent(EVENT_MOUSEDOWN,{x:e.pageX,y:e.pageY,element:e.target.id})},function(e){capture._addEvent(EVENT_MOUSEUP,{x:e.pageX,y:e.pageY,element:e.target.id})},function(e){capture._addEvent(EVENT_CLICK,{x:e.pageX,y:e.pageY,element:e.target.id})},function(e){capture._addEvent(EVENT_KEYPRESS,{keyCode:e.which,element:e.target.id})},function(e){capture._addEvent(EVENT_SCROLL,{x:jQuery(document).scrollLeft(),y:jQuery(document).scrollTop()})},function(e){capture._addEvent(EVENT_RESIZE,capture.screenSize())},function(e){capture._addEvent(EVENT_FOCUS,{element:e.target.id})},function(e){capture._setCookie("post",jQuery(this).attr("action"));var a={};jQuery(this).find(":input").each(function(i){if(jQuery(this).attr("name")){a[jQuery(this).attr("name")]=jQuery(this).val()}});capture._addEvent(EVENT_SUBMIT,{method:jQuery(this).attr("method"),action:jQuery(this).attr("action"),data:a})},function(e){capture._addEvent(EVENT_CHANGE,{element:e.target.id,newValue:e.target.value})},function(e){capture._addEvent(EVENT_BLUR,{element:e.target.id})},function(e){capture._addEvent(EVENT_KEYUP,{element:e.target.id,newValue:jQuery(this).val()})},],start:function(a){this.url=a;this.identifyDOM();this.callbacks[EVENT_RESIZE]();this._bindEvents()},stop:function(){this._unbindEvents();this._persistEvents()},clear:function(){this.events=[];this.details=[];this.times=[];this.timestamp=new Date().getTime()},identifyDOM:function(){var a=document.getElementsByTagName('body')[0].getElementsByTagName('*');for(var i=0;i<a.length;i++){var b=a[i];if(!b.id&&b.tagName!='SCRIPT'&&b.tagName!='STYLE'&&b.tagName!='!'){b.id=this._identifierDOM()}}},screenSize:function(){var a=0,windowHeight=0;if(typeof(window.innerWidth)=='number'){a=window.innerWidth;windowHeight=window.outerHeight}
else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth+15;windowHeight=document.documentElement.clientHeight+200}
else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth+15;windowHeight=document.body.clientHeight+200}
return{x:a,y:windowHeight}},_identifierDOM:function(){return this.prefix+this.separator+++this.index},_addEvent:function(a,b){this.events.push(a);this.details.push(b);this.times.push(new Date().getTime()-this.timestamp);if(this.events.length>EVENT_BUFFER||(jQuery.browser.safari&&a==EVENT_MOUSEDOWN)){this._persistEvents()}
return true},_bindEvents:function(){jQuery(document).bind('mousemove',this.callbacks[EVENT_MOUSEMOVE]);jQuery(document).bind('mousedown',this.callbacks[EVENT_MOUSEDOWN]);jQuery(document).bind('mouseup',this.callbacks[EVENT_MOUSEUP]);jQuery(document).bind('click',this.callbacks[EVENT_CLICK]);jQuery('input[@type="text"]').bind('keypress',this.callbacks[EVENT_KEYPRESS]).bind('keyup',this.callbacks[EVENT_KEYUP]);jQuery(document).bind('scroll',this.callbacks[EVENT_SCROLL]);jQuery(window).bind('resize',this.callbacks[EVENT_RESIZE]);jQuery('input, select').bind('focus',this.callbacks[EVENT_FOCUS]);jQuery('form').bind('submit',this.callbacks[EVENT_SUBMIT]);jQuery(':input').bind('change',this.callbacks[EVENT_CHANGE]);jQuery('input, select').bind('blur',this.callbacks[EVENT_BLUR])},_unbindEvents:function(){jQuery(document).unbind('mousemove',this.callbacks[EVENT_MOUSEMOVE]);jQuery(document).unbind('mousedown',this.callbacks[EVENT_MOUSEDOWN]);jQuery(document).unbind('mouseup',this.callbacks[EVENT_MOUSEUP]);jQuery(document).unbind('click',this.callbacks[EVENT_CLICK]);jQuery('input[@type="text"]').unbind('keypress',this.callbacks[EVENT_KEYPRESS]).unbind('keyup',this.callbacks[EVENT_KEYUP]);jQuery(document).unbind('scroll',this.callbacks[EVENT_SCROLL]);jQuery(window).unbind('resize',this.callbacks[EVENT_RESIZE]);jQuery('input, select').unbind('focus',this.callbacks[EVENT_FOCUS]);jQuery('form').unbind('submit',this.callbacks[EVENT_SUBMIT]);jQuery(':input').unbind('change',this.callbacks[EVENT_CHANGE]);jQuery('input, select').unbind('blur',this.callbacks[EVENT_BLUR])},_persistEvents:function(){var a=new CaptureRequest(this.url,this.timestamp,this.events,this.details,this.times);a.send();this.total+=this.events.length;this.clear()},_setCookie:function(a,b,c){if(c){var d=new Date();d.setTime(d.getTime()+(c*24*60*60*1000));var e="; expires="+d.toGMTString()}
else{var e=""}
document.cookie=a+"="+b+e+"; path=/"},_getCookie:function(a){var b=document.cookie.split(';');var c=a+"=";for(var i=0;i<b.length;i++){var d=b[i];while(d.charAt(0)==' '){d=d.substring(1,d.length)}
if(d.indexOf(c)==0){return d.substring(c.length,d.length)}}
return null},_unsetCookie:function(a){this._setCookie(a,"",-1)}};if(typeof(__userfly_capture_url)!="undefined"){(function(a){jQuery(document).ready(function(){capture.start(a)});jQuery(window).unload(function(){capture.stop()})}
(__userfly_capture_url))}}());