//sunnyGPA http://yoursunny.com/study/GPA/
//Copyright 2010 sunny boy, All rights reserved
var GPA={init:function(){GPA.storage.init();GPA.menu.init();GPA.inputui.init();GPA.alg.init();GPA.calc.init();GPA.resultui.init();GPA.autosave.init();GPA.imp.init();GPA.save.init();GPA.tools.init();GPA.help.init()},server_base:"/study/GPA/2010/",stat:function(a){$.inArray(a,GPA.stat_history)>=0||(GPA.stat_history.push(a),c(GPA.stat_base+a))},stat_base:"/study/GPA/2010/",stat_history:[]};
GPA.popup={open:function(a,b,d){var d=$.extend({width:500,height:350},d),e=0+d.width,d=0+d.height;$("#app_popup_title").width(e+40).text(a).append('<a id="app_popup_close" href="javascript:;">\u00d7</a>');$("#app_popup_close").css("left",e+20).click(GPA.popup.close);$("#app_popup_wrap").width(e+40).height(d+60).css("margin","-"+(d/2+30)+"px 0 0 -"+(e/2+20)+"px");a=$("#app_popup").width(e).height(d).html(b);$("#app_popup_root").show();$("#app_popup_overlay").css("opacity",0);$(window).bind("scroll resize",
GPA.popup.autoMove);GPA.popup.autoMove();return a},get:function(){return $("#app_popup")},close:function(){$("#app_popup").attr("class","");$("#app_popup_root").hide();$(window).unbind("scroll",GPA.popup.window_scroll_handler)},autoMove:function(){var a=$(window);$("#app_popup_root").css("top",a.scrollTop()).height(a.height())}};
GPA.alg={init:function(){$("#alg_change").click(function(){$("#algs").slideDown()});$("#alg_view").click(function(){GPA.alg.viewDetail(GPA.thisAlg)});$("#alg_edit").click(function(){GPA.algedit.start(GPA.thisAlg)});GPA.alg.selectAlg(GPA.predefinedAlg.SJTU);GPA.menu.registerAction("alg",GPA.alg.recentList.prepareMenu);GPA.menu.registerAction("alg_all",function(){$("#algs").slideDown()});GPA.menu.registerAction("alg_predefined",function(a){a=a.data("predefinedAlg_key");GPA.alg.selectAlg(GPA.predefinedAlg[a])});
$("a.alg","#algs").live("click",function(){var a=$(this).attr("data-alg");GPA.stat("alg/"+a);if(/^predefined:/.test(a)){var a=a.substr(11),b=GPA.predefinedAlg[a];b&&GPA.alg.selectAlg(b,a)}$("#algs").slideUp()});GPA.myAlg.init()},selectAlg:function(a,b){GPA.thisAlg=a;a.initialized||a.initialize();$("#alg").trigger("GPA_changeAlg");$("#alg_name").text(a.name);$("#alg_note").html(a.note);$("#alg_detail").hide().html(a.detail);b&&GPA.alg.recentList.push(b)},createAlg:function(a,b,d){var e=function(a,
b){return $.isFunction(a)?e(a(b),b):$.isArray(a)&&$.isFunction(a[0])?e(a[0](b),b):a},f={name:a,author:"",link:"",note:"",initialized:!1};$.extend(f,d||{});f.initialize=function(){var a=f.supportedLevels=[],d=[],i={};$.each(b,function(b,f){if($.isArray(f[0]))d.push(f);else{var j=f[0];$.inArray(a,j)<0&&a.push(j);i[j]=e(f[1],j)}});if(a.length==0)a=f.supportedLevels=null;f.calc=function(b){if(a!=null&&GPA.util.isLevel(b))return i[b];else{var f;$.each(d,function(a,d){var g=d[0];if(g[0]<=b&&b<g[1])return f=
e(d[1],b),!1});return f}};f.getDetail=function(){return b}};return f},viewDetail:function(a){var b="<p>\u7b97\u6cd5\u4f5c\u8005\uff1a"+a.author+"</p>";if(a.link){var d=function(a){return $('<div><a target="_blank"></a></div>').find("a").attr("href",a).text(a).end().html()};b+=$.isArray(a.link)?"<p>\u53c2\u8003\u8d44\u6599\uff1a</p><ul><li>"+$.map(a.link,d).join("</li><li>")+"</li></ul>":"<p>\u53c2\u8003\u8d44\u6599\uff1a"+d(a.link)+"</p>"}d=a.getDetail();if($.isArray(d)){var e="<ul>";$.each(d,function(a,
b){e+="<li>"+($.isArray(b[0])?""+b[0][0]+"\u2264\u5206\u6570\uff1c"+b[0][1]:"\u7b49\u7b2c"+b[0])+"\uff1a"+($.isFunction(b[1])?"\u901a\u8fc7\u51fd\u6570\u8ba1\u7b97":$.isArray(b[1])?$.isFunction(b[1][0])?b[1][1]:"\u7ee9\u70b9"+b[1][0]+"\u3001\u7b49\u7b2c"+b[1][1]:"\u7ee9\u70b9"+b[1])+"</li>"});e+="</ul>";d=e}GPA.popup.open("\u7b97\u6cd5\u7ec6\u8282\uff1a"+a.name,'<div id="alg_detail">'+b+"<hr>"+d+"</div>")},recentList:{fromStorage:function(a){if($.isArray(a)){var b=[],d;$.each(a,function(a,f){var g=
GPA.predefinedAlg[f];g&&(b.push(f),d=g)});GPA.alg.recentList.list=b;d&&(GPA.alg.selectAlg(d),$("#algs").hide())}},push:function(a){var b=GPA.alg.recentList.list;$.inArray(a,b)>=0||(b.push(a),b.length>6&&b.shift(),$("#algs").trigger("GPA_updateRecentAlg"),GPA.alg.recentList.dirtyMenu())},list:[],prepareMenu:function(){var a=$("#menu_alg");if(!a.data("recentAlg")){a.data("recentAlg",!0);var b=$("#menu_alg_sep1");$.each(GPA.alg.recentList.list,function(a,e){var f=GPA.predefinedAlg[e];$("<li>").addClass("enable").addClass("recentAlg").text(f.name).data("menuAction",
"alg_predefined").data("predefinedAlg_key",e).insertAfter(b)})}},dirtyMenu:function(){$("#menu_alg").data("recentAlg",!1).find(".recentAlg").remove()}}};GPA.thisAlg=null;
GPA.oldAlg={parse:function(a){if(/new GPA\.Algorithm\.RangeMap/.test(a))try{return eval(a.replace("new GPA.Algorithm.RangeMap","GPA.oldAlg.RangeMap"))}catch(b){}else if(/new GPA\.Algorithm\.ArithmeticMap/.test(a))try{return eval(a.replace("new GPA.Algorithm.ArithmeticMap","GPA.oldAlg.ArithmeticMap"))}catch(d){}else if(/GPA.Algorithm.ZJU/.test(a))return GPA.predefinedAlg.ZJU;else if(/GPA.Algorithm.PKU7/.test(a))return GPA.predefinedAlg.PKU7},import2009CookieSave:function(){if(!GPA.storage.get("myAlg_import2009CookieSave")&&
(GPA.storage.set("myAlg_import2009CookieSave",!0),/GPA_Algorithm_Saved/.test(document.cookie))){var a=function(a){return(a=document.cookie.match(RegExp("(^|;)\\s*"+escape(a)+"=([^;\\s]*)")))?unescape(a[2]):null}("GPA_Algorithm_Saved");if(a&&a.substr(0,1)=="[")for(a=a.substr(1,a.length-2)+",";a.length>0;){var b=a.match(/\(new GPA\.Algorithm\.RangeMap\('[^\']*'(?:\,[0-9\.]+)*\)\)\,/);if(b){var d=GPA.oldAlg.parse(b[0].substr(0,b[0].length-1));d&&GPA.myAlg.add(d);a=a.substr(b.index+b[0].length)}else break}}},
RangeMap:function(){var a=$.makeArray(arguments),b=a.shift(),d=[];a.unshift(Infinity);a.length%2!=1&&a.push(0);for(var e=1;e<a.length;e+=2)d.push([[a[e+1],a[e-1]],a[e]]);return GPA.alg.createAlg(b,d)},ArithmeticMap:function(a,b){return GPA.alg.createAlg(a,[[[0,Infinity],b]])}};
GPA.predefinedAlg={avg:GPA.alg.createAlg("\u52a0\u6743\u5e73\u5747\u6210\u7ee9",[[[0,Infinity],function(a){return a}]],{author:"\u9633\u5149\u7537\u5b69",note:"\u672c\u7b97\u6cd5\u53ef\u4ee5\u8ba1\u7b97\u52a0\u6743\u5e73\u5747\u6210\u7ee9"}),SJTU:GPA.alg.createAlg("\u4e0a\u6d77\u4ea4\u901a\u5927\u5b66(\u672c\u79d1)",[[[95,100.1],[4.3,"A+"]],[[90,95],[4,"A"]],[[85,90],[3.7,"A-"]],[[80,85],[3.3,"B+"]],[[75,80],[3,"B"]],[[70,75],[2.7,"B-"]],[[67,70],[2.3,"C+"]],[[65,67],[2,"C"]],[[62,65],[1.7,"C-"]],
[[60,62],[1,"D"]],[[0,60],[0,"F"]],["A+",4.3],["A",4],["A-",3.7],["B+",3.3],["B",3],["B-",2.7],["C+",2.3],["C",2],["C-",1.7],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://jwc.sjtu.edu.cn/2007.pdf"}),SJTUg:GPA.alg.createAlg("\u4e0a\u6d77\u4ea4\u901a\u5927\u5b66(\u7814\u7a76\u751f)",[["A+",3.3],["A",3],["A-",2.7],["B+",2.3],["B",2],["B-",1.7],["C",1]],{author:"\u9633\u5149\u7537\u5b69",link:"http://bbs.sjtu.edu.cn/bbstopcon?board=goabroad&file=T.1147958192.A"}),PKU6:GPA.alg.createAlg("\u5317\u4eac\u5927\u5b66(2006\u7ea7\u4ee5\u524d)",
[[[90,100.1],4],[[85,90],3.7],[[82,85],3.3],[[78,82],3],[[75,78],2.7],[[72,75],2.3],[[68,72],2],[[64,68],1.5],[[60,64],1],[[0,60],0],["A",4],["B",3],["C",1],["P",4],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://dean.pku.edu.cn/student/jd.html",note:"\u82e5\u4ee5\u5b57\u6bb5\u8ba1\u7b97\u6210\u7ee9\uff0c\u201c\u4f18\u79c0\u201d\u8bf7\u8f93\u5165A\u3001\u201c\u826f\u597d\u201d\u8bf7\u8f93\u5165B\u3001\u201c\u53ca\u683c\u201d\u8bf7\u8f93\u5165C\u3001\u201c\u4e0d\u53ca\u683c\u201d\u8bf7\u8f93\u5165F\u3001\u201c\u5408\u683c\u201d\u8bf7\u8f93\u5165P\u3001\u201c\u4e0d\u5408\u683c\u201d\u8bf7\u8f93\u5165F\u3002"}),
PKU7:GPA.alg.createAlg("\u5317\u4eac\u5927\u5b66(2007\u7ea7\u4ee5\u540e)",[[[60,100.1],function(a){return 4-3*(100-a)*(100-a)/1600}],[[0,60],0],["A",4],["B",3],["C",1],["P",4],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://dean.pku.edu.cn/student/jd.html",note:"\u82e5\u4ee5\u5b57\u6bb5\u8ba1\u7b97\u6210\u7ee9\uff0c\u201c\u4f18\u79c0\u201d\u8bf7\u8f93\u5165A\u3001\u201c\u826f\u597d\u201d\u8bf7\u8f93\u5165B\u3001\u201c\u53ca\u683c\u201d\u8bf7\u8f93\u5165C\u3001\u201c\u4e0d\u53ca\u683c\u201d\u8bf7\u8f93\u5165F\u3001\u201c\u5408\u683c\u201d\u8bf7\u8f93\u5165P\u3001\u201c\u4e0d\u5408\u683c\u201d\u8bf7\u8f93\u5165F\u3002"}),
US_3:GPA.alg.createAlg("\u7f8e\u56fd4.0(\u00b10.3)",[[[90,100.1],[4,"A"]],[[87,90],[3.7,"A-"]],[[83,87],[3.3,"B+"]],[[80,83],[3,"B"]],[[77,80],[2.7,"B-"]],[[73,77],[2.3,"C+"]],[[70,73],[1.7,"C-"]],[[60,70],[1,"D"]],[[0,60],[0,"F"]],["A+",4],["A",4],["A-",3.7],["B+",3.3],["B",3],["B-",2.7],["C+",2.3],["C",2],["C-",1.7],["D+",1.3],["D",1],["D-",0.7],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:["http://www.taisha.org/bbs/viewthread.php?tid=31209","http://en.wikipedia.org/wiki/Academic_grading_in_the_United_States"]}),
US_5:GPA.alg.createAlg("\u7f8e\u56fd4.0(\u00b10.5)",[[[90,100.1],[4,"A"]],[[85,90],[3.5,"B+"]],[[80,85],[3,"B"]],[[75,80],[2.5,"C+"]],[[70,75],[2,"C"]],[[65,70],[1.5,"D+"]],[[60,65],[1,"D"]],[[0,60],[0,"F"]],["A",4],["B+",3.5],["B",3],["C+",2.5],["C",2],["D+",1.5],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:["http://www.taisha.org/bbs/viewthread.php?tid=31209","http://en.wikipedia.org/wiki/Academic_grading_in_the_United_States"]}),US_10:GPA.alg.createAlg("\u7f8e\u56fd4.0(\u56db\u7ea7)",
[[[90,100.1],[4,"A"]],[[80,90],[3,"B"]],[[70,80],[2,"C"]],[[60,70],[1,"D"]],[[0,60],[0,"F"]],["A",4],["B",3],["C",2],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:["http://www.taisha.org/bbs/viewthread.php?tid=31209","http://en.wikipedia.org/wiki/Academic_grading_in_the_United_States"]}),HongKong:GPA.alg.createAlg("\u9999\u6e2f",[["A+",4.3],["A",4],["A-",3.7],["B+",3.3],["B",3],["B-",2.7],["C+",2.3],["C",2],["C-",1.7],["D+",1.3],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://en.wikipedia.org/wiki/Academic_grading_in_Hong_Kong",
note:"\u672c\u7b97\u6cd5\u4e0d\u652f\u6301\u767e\u5206\u5236\u6210\u7ee9\uff0c\u53ea\u80fd\u8bc6\u522b\u7b49\u7b2c\u5236\u6210\u7ee9"}),SouthKorea:GPA.alg.createAlg("\u97e9\u56fd",[[[95,100.1],[4.5,"A+"]],[[90,95],[4,"A"]],[[85,90],[3.5,"B+"]],[[80,85],[3,"B"]],[[75,80],[2.5,"C+"]],[[70,75],[2,"C"]],[[65,70],[1.5,"D+"]],[[60,65],[1,"D"]],[[0,60],[0,"F"]],["A+",4.5],["B+",3.5],["B",3],["C+",2.5],["C",2],["D+",1.5],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://en.wikipedia.org/wiki/Academic_grading_in_South_Korea"}),
Singapore:GPA.alg.createAlg("\u65b0\u52a0\u5761(Polytechnic)",[[[95,100.1],[4,"AD"]],[[80,95],[4,"A"]],[[75,80],[3.5,"B+"]],[[70,75],[3,"B"]],[[65,70],[2.5,"C+"]],[[60,65],[2,"C"]],[[55,60],[1.5,"D+"]],[[50,55],[1,"D"]],[[0,50],[0,"F"]],["A+",[4,"AD"]],["A",4],["B+",3.5],["B",3],["C+",2.5],["C",2],["D+",1.5],["D",1],["F",0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://en.wikipedia.org/wiki/Academic_grading_in_Singapore#Polytechnic_.28Diploma.29",note:"\u7b49\u7b2c\u201cAD\u201d\u8bf7\u8f93\u5165A+"}),
USTC:GPA.alg.createAlg("\u4e2d\u56fd\u79d1\u6280\u5927\u5b66",[[[95,100.1],4.3],[[90,95],4],[[85,90],3.7],[[82,85],3.3],[[78,82],3],[[75,78],2.7],[[72,75],2.3],[[68,72],2],[[65,68],1.7],[[64,65],1.5],[[61,64],1.3],[[60,61],1],[[0,60],0]],{author:"\u9633\u5149\u7537\u5b69",link:"http://web.yingjiesheng.com/gpa/"}),Canada:GPA.oldAlg.RangeMap("\u52a0\u62ff\u5927",4.3,90,4,85,3.7,80,3.3,75,3,70,2.7,65,2.3,60,0,0),ZJU:GPA.oldAlg.ArithmeticMap("\u6d59\u6c5f\u5927\u5b66",function(a){if(a>=85)return 4;if(a<
60)return 0;return 1.5+(a-60)/10},"GPA.Algorithm.Predefined.ZJU","85 ~ 100 =&gt; 4.0<br/>60 ~ 84 =&gt; 1.5 ~ 3.9\uff08\u5206\u6570\u6bcf\u9ad81\u5206GPA\u589e\u52a00.1\u5206\uff09"),FUDAN:GPA.oldAlg.RangeMap("\u590d\u65e6\u5927\u5b66",4,90,3.7,85,3.3,82,3,78,2.7,75,2.3,71,2,66,1.7,62,1.3,60,0,0),SHU:GPA.oldAlg.RangeMap("\u4e0a\u6d77\u5927\u5b66",4,90,3.7,85,3.3,82,3,78,2.7,75,2.3,72,2,68,1.7,66,1.5,64,1,69,0,0)};
GPA.myAlg={h:{},list:function(){var a=[];$.each(GPA.myAlg.h,function(b){a.push(b)});return a},get:function(a){var b=GPA.myAlg.h[a];return b?GPA.alg.createAlg(a,b.detail,{author:b.author||"",link:b.link||null,note:b.note||"\u81ea\u5b9a\u4e49\u7b97\u6cd5"}):null},add:function(a){a.initialized||a.initialize();GPA.myAlg.h[a.name]={detail:a.getDetail(),author:a.author,link:a.link,note:a.note};GPA.myAlg.dirtyMenu();GPA.myAlg.save()},remove:function(a){delete GPA.myAlg.h[a];GPA.myAlg.dirtyMenu();GPA.myAlg.save()},
init:function(){GPA.menu.registerAction("alg_my",function(a){a=a.data("myAlg_name");GPA.alg.selectAlg(GPA.myAlg.get(a))});var a=GPA.storage.get("myAlg");if($.isPlainObject(a))GPA.myAlg.h=a;GPA.oldAlg.import2009CookieSave();GPA.menu.registerAction("myalg",GPA.myAlg.prepareMenu);GPA.menu.registerAction("myalg_install",GPA.myAlg.install.start);GPA.menu.registerAction("myalg_create",GPA.algedit.startNew);GPA.menu.registerAction("myalg_manage",GPA.myAlg.manager.start)},save:function(){GPA.storage.set("myAlg",
GPA.myAlg.h)},prepareMenu:function(){var a=$("#menu_myalg");if(!a.data("myAlg")){a.data("myAlg",!0);var b=$("#menu_myalg_sep1");$.each(GPA.myAlg.list(),function(a,e){$("<li>").addClass("enable").addClass("myAlg").text(e).data("menuAction","alg_my").data("myAlg_name",e).insertAfter(b)})}},dirtyMenu:function(){$("#menu_myalg").data("myAlg",!1).find(".myAlg").remove()}};
GPA.myAlg.manager={start:function(){GPA.stat("myAlg/manager");GPA.popup.open("\u7ba1\u7406\u6211\u7684\u7b97\u6cd5",'<div id="myalg_manager"></div>');var a=$("<ul>");$.each(GPA.myAlg.list(),function(b,d){var e=$("<a>").text("\u5220\u9664").attr("href","javascript:;").click(function(){GPA.myAlg.remove(d);$(this).closest("li").remove();GPA.stat("myAlg/delete")});a.append($("<li>").text(d+" ").append(e))});$("#myalg_manager").append(a)}};
GPA.myAlg.install={start:function(){GPA.popup.open("\u5b89\u88c5\u65b0\u7b97\u6cd5","<p></p>")}};
GPA.algedit={startNew:function(){GPA.algedit.start(null)},start:function(a){GPA.stat("myAlg/"+(a==null?"new":"edit"));if(GPA.algedit.entryTemplate==null)GPA.algedit.entryTemplate=$('<tr><td><label><input type="radio" name="algedit_entry_t_type" value="grade" checked>\u767e\u5206\u5236</label><br><label><input type="radio" name="algedit_entry_t_type" value="level">\u7b49\u7b2c\u5236</label></td><td><span id="algedit_entry_t_vgrade"><input type="text" id="algedit_entry_t_min" class="algedit_t">\u2264\u5206\u6570\uff1c<input type="text" id="algedit_entry_t_max" class="algedit_t"></span><span id="algedit_entry_t_vlevel" style="display:none;">\u7b49\u7b2c<input type="text" id="algedit_entry_t_level" class="algedit_t"></span></td><td><input type="text" id="algedit_entry_t_point" class="algedit_t"></td><td><input type="text" id="algedit_entry_t_rlevel" class="algedit_t"></td><td><a href="javascript:;" id="algedit_entry_t_delete">\u5220\u9664</a></td></tr>');GPA.popup.open("\u7f16\u8f91\u7b97\u6cd5",
'<form action="" id="algedit_form"><div><p><label>\u7b97\u6cd5\u540d\u79f0\uff1a<input type="text" id="algedit_name"></label><br><label>\u7b97\u6cd5\u5907\u6ce8\uff1a<input type="text" id="algedit_note"></label>(\u652f\u6301HTML\u8bed\u6cd5)</p><table id="algedit_detail_table"><thead><tr><td colspan="2">\u6210\u7ee9</td><td colspan="2">\u7ed3\u679c</td><td>&nbsp;</td></tr><tr><td>\u7c7b\u578b</td><td>\u8303\u56f4</td><td>\u7ee9\u70b9</td><td>\u7b49\u7b2c</td><td>&nbsp;</td></tr></thead><tbody id="algedit_detail"></tbody><tfoot><tr><td colspan="5"><a href="javascript:;" id="algedit_add">\u589e\u52a0\u66f4\u591a\u6761\u76ee</a></td></tr></tfoot></table><p><input type="button" id="algedit_save" value="\u4fdd\u5b58"></p>'+
(GPA.storage.supportLS?"":"<p>\u4f60\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u672c\u5730\u5b58\u50a8\uff0c\u81ea\u5b9a\u4e49\u7b97\u6cd5\u4ec5\u5728\u672c\u6b21\u4f7f\u7528\u6709\u6548\uff1b\u8bf7\u66f4\u6362Firefox3.6\u3001IE8\u7b49\u652f\u6301HTML5\u672c\u5730\u5b58\u50a8\u7684\u6d4f\u89c8\u5668\u3002</p>")+"</div></form>");a!=null&&(a=GPA.algedit.algToForm(a),a===!1?alert("\u8be5\u7b97\u6cd5\u4e0d\u652f\u6301\u7f16\u8f91"):a!==!0&&alert("\u8bd5\u56fe\u6253\u5f00\u7b97\u6cd5\u7f16\u8f91\u5668\uff0c\u4f46\u6709"+
a+"\u4e2a\u6761\u76ee\u5305\u542b\u51fd\u6570\u3001\u65e0\u6cd5\u5bfc\u5165\u3002\n\u56e0\u6b64\uff0c\u6b63\u5728\u7f16\u8f91\u7684\u7b97\u6cd5\u4e0e\u539f\u7b97\u6cd5\u5c06\u6709\u6240\u4e0d\u540c\u3002"));$("#algedit_form").submit(function(){return!1});$("#algedit_add").click(function(){GPA.algedit.addEntry()});$("[id$=_delete]","#algedit_detail").live("click",function(){$(this).closest("tr").remove()});$("[name$=_type]","#algedit_detail").live("click",function(){var a=$(this).closest("tr"),d=a.attr("id").replace("algedit_entry_",
""),a=a.find("[name=algedit_entry_"+d+"_type]:checked").val();$("#algedit_entry_"+d+"_vgrade").toggle(a=="grade");$("#algedit_entry_"+d+"_vlevel").toggle(a=="level")});$("#algedit_save").click(GPA.algedit.save)},algToForm:function(a){$("#algedit_name").val(a.name);$("#algedit_note").val(a.note);var a=a.getDetail(),b=0;if(!$.isArray(a))return!1;$.each(a,function(a,e){GPA.algedit.addEntry(e)||++b});return b==0?!0:b},entryTemplate:null,entry_n:0,addEntry:function(a){var b=$.browser.msie&&$.browser.version<=
7,d,e=++GPA.algedit.entry_n,f="_"+e+"_";d=function(a,b){return b.replace(/_t_/g,f)};d=b?$("<tr>").html(d(-1,GPA.algedit.entryTemplate.html())):GPA.algedit.entryTemplate.clone().find("[id]").attr("id",d).end().find("[name]").attr("name",d).end();d.attr("id","algedit_entry_"+e);b&&$("#algedit_detail").append(d);if(a!=null&&!GPA.algedit.entryToRow(e,a,d))return b&&d.remove(),!1;b||$("#algedit_detail").append(d);return!0},entryToRow:function(a,b,d){var e=function(b){b=b.replace(/%/g,"algedit_entry_"+
a+"_");return d?d.find(b):$(b)};$.isArray(b[0])?(e("[name=%type]").val(["grade"]),e("#%vgrade").show(),e("#%vlevel").hide(),e("#%min").val(b[0][0]),e("#%max").val(b[0][1])):(e("[name=%type]").val(["level"]),e("#%vgrade").hide(),e("#%vlevel").show(),e("#%level").val([b[0]]));if($.isFunction(b[1]))return!1;else if($.isArray(b[1]))if($.isFunction(b[1][0]))return!1;else e("#%point").val(b[1][0]),e("#%rlevel").val(b[1][1]);else e("#%point").val(b[1]),e("#%rlevel").val("");return!0},save:function(){GPA.stat("myAlg/save");
var a=GPA.algedit.algFromForm();GPA.myAlg.add(a);GPA.popup.close();GPA.alg.selectAlg(a)},algFromForm:function(){var a=$("#algedit_name").val();a.length<1&&(a="\u81ea\u5b9a\u4e49 "+(new Date).getTime());var b=$("#algedit_note").val(),d=0,e=[];$("#algedit_detail tr").each(function(){var a=$(this),a=GPA.algedit.entryFromRow(!1,a);GPA.algedit.validateEntry(a)?e.push(a):++d});d>0&&alert("\u5df2\u7ecf\u521b\u5efa\u81ea\u5b9a\u4e49\u7b97\u6cd5\uff0c\u4f46\u662f\u6709"+d+"\u4e2a\u6761\u76ee\u65e0\u6548\u3001\u5df2\u88ab\u5ffd\u7565\u3002");
return GPA.alg.createAlg(a,e,{note:b})},entryFromRow:function(a,b){a===!1&&(a=b.attr("id").replace("algedit_entry_",""));var d=function(b){b=b.replace(/%/g,"algedit_entry_"+a+"_");return $(b)},e=[null,null];switch(d("[name=%type]:checked").val()){case "grade":e[0]=[parseFloat(d("#%min").val()),parseFloat(d("#%max").val())];break;case "level":e[0]=d("#%level").val()}var f=parseFloat(d("#%point").val()),d=d("#%rlevel").val();e[1]=d!=""?[f,d]:f;return e},validateEntry:function(a){if($.isArray(a[0])){if(isNaN(a[0][0])||
isNaN(a[0][1])||a[0][0]>=a[0][1])return!1}else if(!GPA.util.isLevel(a[0]))return!1;if($.isArray(a[1])){if(isNaN(a[1][0]))return!1}else if(isNaN(a[1]))return!1;return!0}};
GPA.menu={init:function(){$("#menubar li").each(function(){var a=$(this),d=a.attr("id").substr(8),e=function(){GPA.menu.invokeAction(d,a);GPA.menu.show(d)};$("#menubar_"+d).click(e).mouseover(function(){GPA.menu.isOpen&&e()})});var a=$("#menus");$("li",a).live("click",function(){var a=$(this);if(a.hasClass("enable")){var d=a.attr("id").substr(5);GPA.menu.invokeAction(d,a)}});$.browser.msie&&($("li.enable",a).live("mouseenter",function(){$(this).addClass("hover")}),$("li.enable",a).live("mouseleave",
function(){$(this).removeClass("hover")}));$("#app").click(function(){GPA.menu.opening?GPA.menu.opening=!1:GPA.menu.hideAll()})},opening:!1,isOpen:!1,invokeAction:function(a,b){var d=b.data("menuAction");typeof d=="function"?d(b):typeof d=="string"?(GPA.menu.actions[d]||$.noop)(b):(GPA.menu.actions[a]||$.noop)(b)},toggleEnabled:function(a,b){$("#menu_"+a).toggleClass("enable",b).toggleClass("disable",!b)},show:function(a){var b=$("#menubar_"+a),d=b.position();d.top+=b.height()+2;GPA.menu.showAt(a,
d)},showAt:function(a,b){GPA.menu.hideAll();var d=$("#menu_"+a);b.pageX&&b.pageY&&(b={left:b.pageX,top:b.pageY});d.css(b).slideDown(300,function(){GPA.menu.opening=!1});GPA.menu.opening=GPA.menu.isOpen=!0},hideAll:function(){$("#menus .menu").stop(!1,!0).hide();GPA.menu.isOpen=!1},actions:{},registerAction:function(a,b){GPA.menu.actions[a]=b}};
GPA.imp={init:function(){GPA.menu.registerAction("input_file",GPA.imp.file.start);GPA.menu.registerAction("input_json",GPA.imp.json.start);GPA.menu.registerAction("input_sjtujwb",GPA.imp.sjtujwb.start)},finish:function(a){var b=!1;GPA.courses.hasCourse()&&(b=confirm(GPA.util.replace_ok_cancel("\u662f\u5426\u6e05\u9664\u5df2\u7ecf\u8f93\u5165\u7684\u8bfe\u7a0b\u4fe1\u606f\uff1f\n\u70b9\u51fb\u3010\u786e\u5b9a\u3011\u6e05\u9664\u5168\u90e8\u5df2\u6709\u8bfe\u7a0b\uff0c\u70b9\u51fb\u3010\u53d6\u6d88\u3011\u5c06\u73b0\u5728\u5bfc\u5165\u7684\u8bfe\u7a0b\u4e0e\u5df2\u6709\u8bfe\u7a0b\u5408\u5e76\u3002")));
GPA.calc.importCourses(a,b);GPA.popup.close()}};
GPA.imp.file={start:function(){GPA.stat("import/file");GPA.popup.open("\u4ece\u6587\u4ef6\u5bfc\u5165",'<form id="import_file_form" action="'+GPA.server_base+'import-file.php" method="post" target="hiddenframe" enctype="multipart/form-data"><div><p>\u4e0a\u4f20\u5305\u542b\u8bfe\u7a0b\u4fe1\u606f\u7684\u6587\u4ef6\uff1a<input id="import_file_upload" name="u" type="file"><span id="import_file_progress" style="display:none;">\u6b63\u5728\u5904\u7406</span></p><p>\u652f\u6301\u7684\u6587\u4ef6\u683c\u5f0f\uff1a</p><ul><li>\u9633\u5149GPA\u8ba1\u7b97\u5668\u5bfc\u51fa\u7684HTML/XHTML\u62a5\u8868\uff08*.htm\uff09</li><li>\u5305\u542b\u6210\u7ee9\u3001\u5b66\u5206\u7b49\u7684EXCEL\u8868\u683c\uff0c\u4fdd\u5b58\u4e3a\u201c\u9017\u53f7\u5206\u9694\u201d\u683c\u5f0f\uff08*.csv\uff09</li><li>\u5305\u542b\u6210\u7ee9\u3001\u5b66\u5206\u7b49\u7684\u6587\u672c\u6587\u4ef6\uff08*.txt\uff09</li></ul></div></form>',{height:200});
$("#import_file_upload").bind("change click",GPA.imp.file.upload_change)},upload_change:function(){$("#import_file_upload").val()!=""&&($("#import_file_upload").hide(),$("#import_file_progress").show(),$("#import_file_form").submit())},handleResult:function(a,b,d){d&&alert(d);switch(a){case 1:$("#import_file_form").get(0).reset();$("#import_file_progress").hide();$("#import_file_upload").show();break;case 2:GPA.stat("import/file.ok");GPA.imp.finish(b.courses);break;case 3:GPA.imp.csv.run(b)}GPA.util.reset_hiddenframe()}};
GPA.imp.csv={run:function(a){GPA.stat("import/csv");var b=GPA.imp.csv;$.extend(b,{data:a,hasHeader:!1,delimeter:",",enclosure:'"',escape:"\\",col_name:-1,col_credit:-1,col_grade:-1});b.detectHeader()?b.processCourses():(b.detectDelimeter(),b.detectColumns(),b.renderForm())},re_name_header:/\u8bfe\u7a0b|\u540d\u79f0|course|name|\u79d1\u76ee|\u8bfe\u76ee|\u5b66\u79d1/i,re_credit_header:/\u5b66\u5206|credit/i,re_grade_header:/\u6210\u7ee9|\u5206\u6570|\u5f97\u5206|\u8bc4\u5206|grade|score/i,detectKnownHeader:function(a){var b=
GPA.imp.csv;switch(a){case "\u8bfe\u7a0b,\u5b66\u5206,\u6210\u7ee9":return b.col_name=0,b.col_credit=1,b.col_grade=2,!0}return!1},detectHeader:function(){var a=GPA.imp.csv,b=a.data;if(b.length<=1)return!1;b=b[0];if(a.detectKnownHeader(b))return a.hasHeader=!0;if(a.re_name_header.test(b)||a.re_credit_header.test(b)||a.re_grade_header.test(b))a.hasHeader=!0;return!1},detectDelimeter:function(){var a=GPA.imp.csv,b=a.data;if(b.length!=0&&(b=b[Math.floor(b.length/2)],!(GPA.util.getcsv(b,a).length>=2)&&
(a.delimeter="\t",!(GPA.util.getcsv(b,a).length>=2)&&(a.delimeter=" ",!(GPA.util.getcsv(b,a).length>=2)&&(a.delimeter=";",!(GPA.util.getcsv(b,a).length>=2))))))a.delimeter=","},detectColumns:function(){var a=GPA.imp.csv;if(a.hasHeader){var b=GPA.util.getcsv(a.data[0],a);if(!(b.length<2))for(var d=b.length-1;d>=0;--d){if(a.re_name_header.test(b[d]))a.col_name=d;if(a.re_credit_header.test(b[d]))a.col_credit=d;if(a.re_grade_header.test(b[d]))a.col_grade=d}}},form_delimeters:{",":"comma","\t":"tab"," ":"space",
";":"semicolon"},renderForm:function(){var a=GPA.imp.csv;GPA.popup.open("CSV\u5bfc\u5165\u9009\u9879",'<form id="import_csv_form" action=""><div><p><input type="button" id="import_csv_ok" value="\u786e\u5b9a\u5e76\u7ee7\u7eed"> <input type="button" id="import_csv_cancel" value="\u91cd\u65b0\u4e0a\u4f20"></p><p id="import_csv_set1">\u5206\u9694\u7b26\u53f7 <label><input type="radio" name="delimeter" id="import_csv_delimeter_comma">\u9017\u53f7(,)</label> <label><input type="radio" name="delimeter" id="import_csv_delimeter_tab">TAB</label> <label><input type="radio" name="delimeter" id="import_csv_delimeter_space">\u7a7a\u683c</label> <label><input type="radio" name="delimeter" id="import_csv_delimeter_semicolon">\u5206\u53f7(;)</label> <label><input type="radio" name="delimeter" id="import_csv_delimeter_other">\u5176\u4ed6</label><input type="text" id="import_csv_delimeter_char" maxlength="1" size="3"> <label><input type="checkbox" id="import_csv_hasheader">\u7b2c\u4e00\u884c\u4f5c\u4e3a\u6807\u9898\u884c</label></p><div id="import_csv_preview"></div></div></form>');
var b=a.form_delimeters[a.delimeter];b?$("#import_csv_delimeter_"+b).prop("checked",!0):($("#import_csv_delimeter_other").prop("checked",!0),$("#import_csv_delimeter_char").val(a.delimeter));$("#import_csv_hasheader").prop("checked",a.hasHeader);$("#import_csv_delimeter_other").click(function(){this.checked&&$("#import_csv_delimeter_char").focus()});$("#import_csv_set1").change(function(){a.collectSettings();a.renderPreview()});$("#import_csv_form").submit(function(){return!1});$("#import_csv_ok").click(GPA.imp.csv.okClick);
$("#import_csv_cancel").click(GPA.imp.file.start);a.renderPreview()},renderPreview:function(){var a=GPA.imp.csv,b=a.data,d=$("<table><thead></thead><tbody></tbody></table>"),e=d.find("thead"),f=null,g=d.find("tbody"),h=-1;$.each(b,function(b,d){var e=GPA.util.getcsv(d,a),m=$("<tr><th>&nbsp;</th></tr>");$.each(e,function(a,b){h=Math.max(h,a);var d=$("<td>");b==""?d.html("&nbsp;"):d.text(b);m.append(d)});a.hasHeader&&b==0?f=m:g.append(m);if(b>=20)return!1});$.each({name:"\u8bfe\u7a0b\u540d\u79f0",credit:"\u5b66\u5206",
grade:"\u6210\u7ee9"},function(b,d){for(var f=$("<tr><th></th></tr>").find("th").text("\u4f5c\u4e3a\uff1a"+d).end(),g=0;g<=h;++g){var i=$('<td><input type="radio" name="colsel_'+b+'"'+(a["col_"+b]==g?"checked":"")+' value="'+g+'"></td>');f.append(i)}e.append(f)});f&&e.prepend(f);for(var b=$("<tr><th>&nbsp;</th></tr>"),i=0;i<=h;++i)b.append("<td>\u7b2c"+(i+1)+"\u5217</td>");e.prepend(b);$("#import_csv_preview").html(d)},collectSettings:function(){var a=GPA.imp.csv,b=$("#import_csv_preview");if($("#import_csv_delimeter_other").is(":checked")){if(a.delimeter=
$("#import_csv_delimeter_char").val(),a.delimeter.length!=1)a.delimeter=",",$("#import_csv_delimeter_char").val(",")}else $.each(a.form_delimeters,function(b,e){if($("#import_csv_delimeter_"+e).is(":checked"))a.delimeter=b});a.hasHeader=$("#import_csv_hasheader").is(":checked");$.each(["name","credit","grade"],function(d,e){var f=b.find(":radio[name=colsel_"+e+"]:checked");a["col_"+e]=f.length>0?parseInt(f.val()):-1})},okClick:function(){var a=GPA.imp.csv;a.collectSettings();a.checkSettings()&&a.processCourses();
GPA.stat("import/csv.ok")},checkSettings:function(){var a=GPA.imp.csv;if(a.col_credit<0)return alert("\u8bf7\u6307\u5b9a\u5b66\u5206\u5217"),!1;if(a.col_grade<0)return alert("\u8bf7\u6307\u5b9a\u6210\u7ee9\u5217"),!1;return!0},processCourses:function(){var a=GPA.imp.csv,b=[],d=[];$.each(a.data,function(e,f){if(!(e==0&&a.hasHeader)){var g=GPA.util.getcsv(f,a),g={selected:!0,name:a.col_name>=0?g[a.col_name]:"",credit:parseFloat(g[a.col_credit]),grade:GPA.util.parseLevelOrGrade(g[a.col_grade])};isNaN(g.credit)||
isNaN(g.grade)?d.push(f):b.push(g)}});(!(d.length>0)||confirm(GPA.util.replace_ok_cancel("\u6709"+d.length+"\u95e8\u8bfe\u7a0b\u7684\u5b66\u5206\u548c/\u6216\u6210\u7ee9\u65e0\u6cd5\u8bc6\u522b\uff0c\u53ef\u80fd\u662f\u5217\u6307\u5b9a\u9519\u8bef\u3002\n\u70b9\u51fb\u3010\u786e\u5b9a\u3011\u5ffd\u7565\u9519\u8bef\u5e76\u7ee7\u7eed\uff0c\u70b9\u51fb\u3010\u53d6\u6d88\u3011\u8fd4\u56de\u4fee\u6539\u3002\n\n\u9519\u8bef\u884c\u4e3e\u4f8b\uff1a\n"+d[0])))&&GPA.imp.finish(b)}};
GPA.imp.json={start:function(){GPA.stat("import/json");GPA.popup.open("\u4eceJSON\u4ee3\u7801\u5bfc\u5165",'<p>\u8bf7\u6309\u3010CTRL+V\u3011\u7c98\u8d34\u4e0a\u6b21\u5bfc\u51fa\u7684JSON\u4ee3\u7801\uff0c\u4ee3\u7801\u4e0d\u80fd\u4fee\u6539\u3002</p><textarea id="import_json_input"></textarea><p><input type="button" id="import_json_ok" value="\u786e\u5b9a"></p>',{height:200}).show();$("#import_json_ok").click(GPA.imp.json.okClick)},okClick:function(){GPA.imp.json.jsonData=$("#import_json_input").val();
GPA.imp.json.processData()},jsonData:"",processData:function(){var a,b=null;if(GPA.imp.json.jsonData=="")alert("JSON\u4ee3\u7801\u4e3a\u7a7a\u3002");else{try{a=$.parseJSON(GPA.imp.json.jsonData)}catch(d){alert("JSON\u4ee3\u7801\u89e3\u6790\u5931\u8d25\u3002");return}a==null?alert("JSON\u89e3\u6790\u7ed3\u679c\u4e3a\u7a7a\u3002"):(a=GPA.imp.json.parseJSON(a),(b=a[1])?(GPA.stat("import/json."+a[0]),GPA.imp.finish(b)):alert(a[0]))}},parseJSON:function(a){if($.isArray(a)){if(a.length==0)return["JSON\u6570\u7ec4\u4e0d\u5305\u542b\u8bfe\u7a0b\u4fe1\u606f\u3002",
!1];if($.isPlainObject(a[0])&&typeof a[0].id=="string"&&typeof a[0].name=="string"&&typeof a[0].credit=="number"&&typeof a[0].grade=="number"&&typeof a[0].code=="string"&&typeof a[0].selected=="boolean")return a=GPA.imp.json.parseJSON2009(a),["2009",a]}else if($.isPlainObject(a)&&a.version=="95ed3d84-6d7d-4e49-b9db-db27d16ec322")return a=GPA.imp.json.parseJSON95ed3d84(a),["95ed3d84",a];return["\u4e0d\u80fd\u8bc6\u522bJSON\u6570\u636e\u7684\u683c\u5f0f\u3002",!1]},parseJSON2009:function(a){return $.map(a,
function(a){return{selected:a.selected,name:a.name,credit:a.credit,grade:a.grade,groups:""}})},parseJSON95ed3d84:function(a){return a.courses}};
GPA.imp.sjtujwb={start:function(){GPA.stat("import/sjtujwb");GPA.popup.open("\u901a\u8fc7\u4e0a\u6d77\u4ea4\u901a\u5927\u5b66\u4fee\u4e1a\u67e5\u8be2\u5bfc\u5165",'<p>\u8bbf\u95ee\u4e0a\u6d77\u4ea4\u901a\u5927\u5b66\u6559\u52a1\u529e<a href="http://jwb.jwc.sjtu.edu.cn/xsbyshj/" target="_blank">\u672c\u79d1\u4fee\u4e1a\u60c5\u51b5\u67e5\u8be2</a>\uff0c\u7528\u4f60\u7684jAccount\u767b\u5f55(\u7528\u6237\u540d\u5bc6\u7801\u4e0e\u4ea4\u5927\u90ae\u7bb1\u3001portal\u4e2a\u4eba\u5b58\u50a8FTP\u76f8\u540c)\u3002\u51fa\u73b0\u7ed3\u679c\u540e\uff0c\u6309\u4e0bCTRL+A\u952e\u5168\u9009\uff0c\u6309\u4e0bCTRL+C\u952e\u590d\u5236\uff0c\u7136\u540e\u70b9\u51fb\u4e0b\u9762\u7684\u6587\u672c\u6846\u3001\u6309\u4e0bCTRL+V\u952e\u7c98\u8d34\u3002</p><textarea id="import_sjtujwb_input"></textarea><p><input type="button" id="import_sjtujwb_ok" value="\u786e\u5b9a"></p><p>\u5206\u7ec4\u4ee3\u53f7\uff1a1~8=\u5b66\u671f\u6b21\u5e8f\uff0cR=\u5fc5\u4fee\uff0cL=\u9650\u9009\uff0cG=\u901a\u9009\uff0cF=\u4efb\u9009</p>',{height:300});
$("#import_sjtujwb_ok").click(GPA.imp.sjtujwb.okClick);if($.fn.xheditor)GPA.imp.sjtujwb.onXHEready();else W.loadjs("/lib/10/xheditor-en.js",GPA.imp.sjtujwb.onXHEready);$.browser.opera&&$("#import_sjtujwb_ok").after("\u6b64\u529f\u80fd\u5728Opera\u4e2d\u53ef\u80fd\u4e0d\u80fd\u6b63\u5e38\u5de5\u4f5c\u3002")},onXHEready:function(){$("#import_sjtujwb_input").xheditor(!0,{tools:"About"})},okClick:function(){GPA.stat("import/sjtujwb.ok");var a=$("#import_sjtujwb_input").get(0).objxhe.getSource(),a=GPA.imp.sjtujwb.parseReport($("<div>").html(a));
GPA.imp.finish(a)},parseReport:function(a){var b=[],d=9999,e=["R","L","G","F"];a.find("table").each(function(){var a=$(this).find("tr");if(!(a.length<2)){var g=-1,h=-1,i=-1,k=-1,l=-1;a.first().find("th,td").each(function(a){var b=$(this);/\u8bfe\u7a0b\u540d\u79f0/.test(b.text())&&(g=a);/\u5b66\u5206/.test(b.text())&&(h=a);/\u6210\u7ee9/.test(b.text())&&(i=a);/\u5b66\u5e74/.test(b.text())&&(k=a);/\u5b66\u671f/.test(b.text())&&(l=a)});if(!(g<0||h<0||i<0||k<0||l<0)){var j=e.length>0?e.shift():"";a.slice(1).each(function(){var a=
$(this).find("th,td"),a={selected:!0,name:$.trim(a.eq(g).text()),credit:parseFloat(a.eq(h).text()),grade:parseFloat(a.eq(i).text()),sjtu_schoolyear:parseInt(a.eq(k).text().split("-")[0]),sjtu_term:parseInt(a.eq(l).text()),groups:j};d=Math.min(d,a.sjtu_schoolyear);!isNaN(a.credit)&&!isNaN(a.grade)&&b.push(a)})}}});$.each(b,function(a,b){b.groups+=(b.sjtu_schoolyear-d)*2+b.sjtu_term});return b}};
GPA.save={init:function(){GPA.menu.registerAction("save",GPA.save.prepareMenu);GPA.menu.registerAction("save_file",GPA.save.file.start);GPA.menu.registerAction("save_json",GPA.save.json.start);GPA.menu.registerAction("save_email",GPA.save.file.start_email)},prepareMenu:function(){var a=GPA.courses.hasCourse();GPA.menu.toggleEnabled("save_file",a);GPA.menu.toggleEnabled("save_json",a);GPA.menu.toggleEnabled("save_email",a)},finish:function(){GPA.popup.close()}};
GPA.save.file={start:function(){GPA.stat("save/file");GPA.save.file.is_email=!1;GPA.save.file.start1()},start_email:function(){GPA.stat("save/email");GPA.save.file.is_email=!0;GPA.save.file.start1()},is_email:!1,start1:function(){var a=GPA.save.file.is_email;GPA.popup.open(a?"\u4fdd\u5b58\u5230\u4fe1\u7bb1":"\u4fdd\u5b58\u4e3a\u6587\u4ef6",'<form id="save_file_form" action="'+GPA.server_base+'save-file.php" method="POST" target="hiddenframe"><div><input type="hidden" id="save_file_data" name="data"><table><thead><tr><th>\u6587\u4ef6\u683c\u5f0f</th><td>\u4e0b\u6b21\u53ef\u5bfc\u5165</td><td>\u8bfe\u7a0b\u4fe1\u606f</td><td>\u8ba1\u7b97\u7ed3\u679c</td><td>\u7b97\u6cd5</td><td>\u5206\u7ec4</td></tr></thead><tbody><tr><th><label><input type="radio" name="format" value="htm" checked>HTML\u62a5\u8868(*.htm)</label></th><td>\u221a</td><td>\u221a</td><td>\u221a</td><td>\u00d7</td><td>\u221a</td></tr><tr><th><label><input type="radio" name="format" value="csv">\u9017\u53f7\u5206\u9694\u8868\u683c(*.csv)</label></th><td>\u221a</td><td>\u221a</td><td>\u00d7</td><td>\u00d7</td><td>\u00d7</td></tr>'+
(a?"":'<tr><th><label><input type="radio" name="format" value="xlsx">Excel\u6587\u6863(*.xlsx)</label></th><td>\u00d7</td><td>\u221a</td><td>\u221a</td><td>\u00d7</td><td>\u00d7</td></tr>')+"</tbody></table>"+(a?'<p>\u53d1\u9001\u5230\u4f60\u7684\u4fe1\u7bb1\uff1a<input type="text" id="save_file_email" name="email"></p><p><input type="submit" value="\u53d1\u9001\u7535\u5b50\u90ae\u4ef6"><input type="hidden" name="mode" value="email">':'<p><input type="submit" value="\u5bfc\u51fa\u6587\u4ef6">')+"</p></div></form>",
{height:250}).show();$("#save_file_data").val(GPA.save.file.serializeData());$("#save_file_form").submit(GPA.save.file.onSubmitForm)},serializeData:function(){var a=[],b;GPA.courses.each(function(b,e){a.push($.param(e))});b=GPA.calc.getResult();return $.param({courses:a.join("|"),alg:"",result:$.param(b)})},onSubmitForm:function(){var a=$("#save_file_form"),b=a.find("[name=format]:checked").val();GPA.save.file.is_email?GPA.stat("save/email."+b):(GPA.stat("save/file."+b),b=="xlsx"&&a.attr("action",
"http://n.65536.cn/yoursunny/GPA_save-xlsx.ashx"),setTimeout(GPA.popup.close,2E3))},handleEmailResult:function(a){a=(""+a).split("/");switch(a[0]){case "invalid":switch(a[1]){case "hash":alert("\u90ae\u4ef6\u53c2\u6570\u9519\u8bef\uff0c\u8bf7\u91cd\u8bd5\u6216\u8054\u7cfb\u5f00\u53d1\u8005");break;case "to":alert("\u4fe1\u7bb1\u5730\u5740\u4e0d\u6b63\u786e")}break;case "ex":alert("\u53d1\u9001\u90ae\u4ef6\u5f02\u5e38\n"+a[1]);break;case "OK":alert("\u90ae\u4ef6\u53d1\u9001\u6210\u529f\uff0c\u8bf7\u67e5\u6536\u6765\u81ea\u4e0b\u5217\u5730\u5740\u7684\u90ae\u4ef6\uff1a\n"+
a[1]),GPA.save.finish()}}};
GPA.save.json={start:function(){GPA.stat("save/json");GPA.popup.open("\u4fdd\u5b58\u4e3aJSON\u4ee3\u7801",'<div id="save_json"><p>\u8bf7\u590d\u5236\u4ee3\u7801\u5e76\u59a5\u5584\u4fdd\u5b58\uff0c\u4ee3\u7801\u4e0d\u80fd\u4fee\u6539\uff1a</p><textarea id="save_json_code"></textarea><p><input type="button" id="save_json_ok" value="\u5173\u95ed"></p></div>',{height:200}).show();$("#save_json_code").text(GPA.save.json.getCoursesJSON());$("#save_json_ok").click(GPA.save.finish)},getCoursesJSON:function(){var a=
{version:"95ed3d84-6d7d-4e49-b9db-db27d16ec322",courses:[]};GPA.courses.each(function(b,d){a.courses.push({selected:d.selected,name:d.name,credit:d.credit,grade:d.grade,groups:d.groups})});return $.toJSON(a)}};
GPA.inputui={init:function(){GPA.inputui.addEmptyRows();$("#C_all_delete").click(function(){confirm("\u662f\u5426\u5220\u9664\u6240\u6709\u8bfe\u7a0b\u4fe1\u606f\uff1f\n\uff08\u65e0\u6cd5\u6062\u590d\uff09")&&(GPA.inputui.removeAllRows(),GPA.stat("input/removeAll"))});$("#course_add").click(function(){for(var a=0;a<5;++a)GPA.inputui.addRow()});$("#courses").bind("GPA_changeCourse",GPA.inputui.onChangeCourse).bind("GPA_removeCourse",GPA.inputui.onRemoveCourse).keyup(GPA.inputui.onKeyUp);$("#courses_table").attr("cellspacing",
0)},addEmptyRows:function(){for(var a=0;a<10;++a)GPA.inputui.addRow()},last_change_evt_target:null,addRow:function(a,b){a||(a=GPA.courses.generate_id());var d=$("#course_template").clone().attr("id","C_"+a);d.find("[id^=C_i_]").each(function(){this.id=this.id.replace("_i_","_"+a+"_")});var e=function(b){GPA.inputui.last_change_evt_target=b.target;d.trigger("GPA_changeCourse",[a])};d.find(":text").blur(e);d.find(":checkbox").click(e);d.find("#C_"+a+"_delete").click(function(){d.trigger("GPA_removeCourse",
[a])});$("#courses").append(d);b&&GPA.inputui.courseToRow(a,b);d.show().trigger("GPA_addCourse",[a])},courseFromRow:function(a){a={selected:$("#C_"+a+"_selected").is(":checked"),name:$("#C_"+a+"_name").val(),credit:parseFloat($("#C_"+a+"_credit").val()),grade:$("#C_"+a+"_grade").val(),groups:GPA.util.parseGroups($("#C_"+a+"_groups").val())};return a.credit&&a.grade?a:null},courseToRow:function(a,b){var d=function(b){if(b=="#%")return $("#C_"+a);b=b.replace(/%/g,"C_"+a+"_");return $(b)};d("#%selected").prop("checked",
b.selected);d("#%name").val(b.name);d("#%credit").val(b.credit);d("#%grade").val(b.grade);d("#%groups").val(b.groups);GPA.inputui.courseResultToRow(a,b)},courseResultToRow:function(a,b,d){d=d||function(b){if(b=="#%")return $("#C_"+a);b=b.replace(/%/g,"C_"+a+"_");return $(b)};d("#%").toggleClass("NaN",isNaN(b.point));d("#%level").html(b.level==""?"&nbsp;":b.level);d("#%point").text(isNaN(b.point)?"\u4e0d\u652f\u6301":GPA.util.fix1(b.point));d("#%cp").text(isNaN(b.cp)?"\u4e0d\u652f\u6301":GPA.util.fix1(b.cp))},
removeAllRows:function(){$("#courses tr").each(function(){var a=$(this),b=a.attr("id").substr(2);a.trigger("GPA_removeCourse",[b])})},removeEmptyRows:function(){$("#courses tr").each(function(){var a=!1;$(":text",this).each(function(){this.value!=""&&(a=!0)});if(!a){var b=$(this),d=b.attr("id").substr(2);b.trigger("GPA_removeCourse",[d])}})},popupCourseInvalidTop:function(a){a=$("#C_"+a+"_selected").position();a.top-=33;var b=$("#course_invalid_tip").css(a).show();setTimeout(function(){b.fadeOut(1E3)},
1E3)},onKeyUp:function(a){switch(a.which){case 13:a=$(a.target).closest("td");if(a.length==0)break;var b=a.nextAll("td:has(:text)").first();if(b.length>0)b.find(":text").focus();else{var b=a.closest("tr"),d=b.next("tr");d.length==0&&(GPA.inputui.addRow(),d=b.next("tr"));d.find("td :text:first").focus()}a.find("input").triggerHandler("blur")}},onChangeCourse:function(a,b){var d=$("#C_"+b+"_name");d.val($.trim(d.val()));var e=$("#C_"+b+"_credit"),d=GPA.util.normalizeFloat(e.val());e.val(d);var f=$("#C_"+
b+"_grade"),e=GPA.util.parseLevelOrGrade(f.val());f.val(e);var f=$("#C_"+b+"_groups"),g=GPA.util.parseGroups(f.val());f.val(g);f=$("#C_"+b+"_selected");g=f.index(GPA.inputui.last_change_evt_target)>=0;d&&e?g||f.prop("checked",!0):g&&(f.prop("checked",!1),GPA.inputui.popupCourseInvalidTop(b))},onRemoveCourse:function(a,b){$("#C_"+b).remove()}};
GPA.resultui={init:function(){$("#app").bind("GPA_invalidateResult",function(){GPA.resultui.render(GPA.calc.getResult())});$.browser.msie&&$.browser.version==6&&($("#calc_result_float").css("position","absolute"),$(window).bind("resize scroll",GPA.resultui.calc_result_float_move),GPA.resultui.calc_result_float_move())},render:function(a){a.course_count==0||a.credit_total==0?($("#result_credit_total,#result_gpa,#result_cp_total").html("&nbsp;"),$("#calc_result_float").removeClass("NaN").text("\u6b22\u8fce\u4f7f\u7528\u9633\u5149GPA\u8ba1\u7b97\u5668\uff01")):
($("#result_credit_total").text("\u2211="+a.credit_total),$("#result_gpa").html('<span style="text-decoration:overline;">x</span>='+(isNaN(a.GPA)?"\u65e0\u7ed3\u679c":GPA.util.fix4(a.GPA))),$("#result_cp_total").text("\u2211="+(isNaN(a.cp_total)?"\u65e0\u7ed3\u679c":GPA.util.fix1(a.cp_total))),isNaN(a.GPA)?$("#calc_result_float").addClass("NaN").text("\u90e8\u5206\u6210\u7ee9\u65e0\u6cd5\u8bc6\u522b\uff0c\u672a\u80fd\u7b97\u51fa\u7ed3\u679c\uff1b\u8bf7\u66f4\u6b63\u9519\u8bef\u7684\u6210\u7ee9"):
$("#calc_result_float").removeClass("NaN").text(""+a.course_count+"\u95e8\u8bfe\u7a0b\uff0c\u603b\u5b66\u5206="+a.credit_total+"\uff0cGPA="+GPA.util.fix4(a.GPA)))},calc_result_float_move:function(){var a=$(window),b=$("#calc_result_float");b.css("top",a.scrollTop()+a.height()-b.outerHeight())}};
GPA.courses={a:[],h:{},last_id:0,generate_id:function(){return++GPA.courses.last_id},get:function(a){a=parseInt(a);return GPA.courses.h[a]},set:function(a,b){a=parseInt(a);if(!b.groups)b.groups="";GPA.courses.h[a]=b;$.inArray(a,GPA.courses.a)<0&&GPA.courses.a.push(a)},remove:function(a){var a=parseInt(a),b=$.inArray(a,GPA.courses.a);b>=0&&(GPA.courses.a.splice(b,1),delete GPA.courses.h[a])},each:function(a,b){b?b===!0&&(b=function(a,b){return b.selected}):b=function(){return!0};$.each(GPA.courses.a,
function(d,e){var f=GPA.courses.h[e];b(e,f)&&a(e,f)})},hasCourse:function(){return GPA.courses.a.length>0}};GPA.collector=function(a){this.filter=a};
$.extend(GPA.collector.prototype,{fresh:!1,course_count:0,credit_total:0,cp_total:0,collectAll:function(){var a=this;a.course_count=a.credit_total=a.cp_total=0;GPA.courses.each(function(b,d){++a.course_count;a.credit_total+=d.credit;a.cp_total+=d.cp},a.filter);a.fresh=!0},invalidateResult:function(){this.fresh=!1},getResult:function(){this.fresh||this.collectAll();return{course_count:this.course_count,credit_total:this.credit_total,cp_total:this.cp_total,GPA:this.cp_total/this.credit_total}}});
GPA.calc={init:function(){$("#app").bind("GPA_addCourse",GPA.calc.onAddCourse).bind("GPA_changeCourse",GPA.calc.onChangeCourse).bind("GPA_removeCourse",GPA.calc.onRemoveCourse).bind("GPA_changeAlg",function(){GPA.calc.calcAllCourses();GPA.calc.invalidateResult()})},calcCourse:function(a){var b=GPA.thisAlg,d="",e=a.grade;if(GPA.util.isLevel(e)){if(b.supportedLevels==null||b.supportedLevels.length==0){a.point=NaN;a.level="";a.cp=NaN;return}$.inArray(e,b.supportedLevels)<0&&(e=GPA.util.translateLevel(e,
b.supportedLevels));d=a.level}else typeof e=="string"&&(e=parseFloat(e));b=b.calc(e);$.isArray(b)?(a.point=b[0],a.level=b[1]):(a.point=b,a.level=d);a.cp=a.point*a.credit},calcAllCourses:function(){GPA.courses.each(function(a,b){GPA.calc.calcCourse(b);GPA.inputui.courseResultToRow(a,b)})},mainCollector:new GPA.collector(!0),pause_invalidate_evt:!1,invalidateResult:function(){GPA.calc.mainCollector.invalidateResult();GPA.calc.pause_invalidate_evt||$("#courses").trigger("GPA_invalidateResult")},getResult:function(){return GPA.calc.mainCollector.getResult()},
importCourses:function(a,b){GPA.calc.pause_AddCourse=GPA.calc.pause_invalidate_evt=!0;b?GPA.inputui.removeAllRows():GPA.inputui.removeEmptyRows();$.each(a,function(a,b){var f=GPA.courses.generate_id();GPA.courses.set(f,b);GPA.calc.calcCourse(b);GPA.inputui.addRow(f,b)});a.length==0&&b&&GPA.inputui.addEmptyRows();GPA.calc.pause_AddCourse=GPA.calc.pause_invalidate_evt=!1;GPA.calc.invalidateResult()},pause_AddCourse:!1,onAddCourse:function(a,b){if(!GPA.calc.pause_AddCourse){var d=GPA.inputui.courseFromRow(b);
d!=null&&(GPA.courses.set(b,d),GPA.calc.calcCourse(d),GPA.inputui.courseResultToRow(b,d),d.selected&&GPA.calc.invalidateResult())}},onChangeCourse:function(a,b){var d=GPA.courses.get(b);d!=null&&d.selected&&GPA.calc.invalidateResult();var e=GPA.inputui.courseFromRow(b);e==null?d!=null&&GPA.courses.remove(b):(GPA.courses.set(b,e),GPA.calc.calcCourse(e),GPA.inputui.courseResultToRow(b,e),GPA.calc.invalidateResult())},onRemoveCourse:function(a,b){var d=GPA.courses.get(b);GPA.courses.remove(b);d!=null&&
d.selected&&GPA.calc.invalidateResult()}};
GPA.tools={init:function(){GPA.menu.registerAction("tools",GPA.tools.prepareMenu);GPA.menu.registerAction("tools_translate",GPA.translate.start);GPA.menu.registerAction("tools_chart",GPA.chart.start);GPA.menu.registerAction("tools_bygroup",function(){GPA.bygroup.start("menu-tools")});$("#result_bygroup").click(function(){GPA.bygroup.start("inputui-bottom")})},prepareMenu:function(){var a=GPA.courses.hasCourse();GPA.menu.toggleEnabled("tools_translate",a);GPA.menu.toggleEnabled("tools_chart",a)}};
GPA.translate={start:function(){GPA.stat("tools/translate");GPA.popup.open("\u7ffb\u8bd1\u8bfe\u7a0b\u540d\u79f0",'<form id="translate_form" action=""><div><p>\u76ee\u6807\u8bed\u8a00\uff1a<br><label><input type="radio" name="lang" value="English" checked>\u82f1\u8bed</label><br><label><input type="radio" name="lang" value="French">\u6cd5\u8bed</label><br><label><input type="radio" name="lang" value="German">\u5fb7\u8bed</label><br><label><input type="radio" name="lang" value="Italian">\u610f\u5927\u5229\u8bed</label><br><label><input type="radio" name="lang" value="Japanese">\u65e5\u8bed</label><br></p><p>\u7ffb\u8bd1\u7ed3\u679c\uff1a<br><label><input type="radio" name="result" value="below" checked>\u663e\u793a\u5728\u4e0b\u65b9</label> \u62a5\u8868\u4ecd\u663e\u793a\u539f\u59cb\u8bfe\u7a0b\u540d<br><label><input type="radio" name="result" value="replace">\u66ff\u6362\u539f\u8bfe\u7a0b\u540d</label> \u62a5\u8868\u5c06\u663e\u793a\u7ffb\u8bd1\u540e\u7684\u5916\u6587\u8bfe\u7a0b\u540d<br></p><p><input type="button" id="translate_ok" value="\u7ffb\u8bd1\u8bfe\u7a0b\u540d\u79f0"></p><p>\u7ffb\u8bd1\u670d\u52a1\uff1a\u4e0a\u6d77\u4ea4\u901a\u5927\u5b66\u6559\u52a1\u5904\u8bfe\u7a0b\u82f1\u6587\u540d\u79f0\u67e5\u8be2\uff0cBing Translator</p><div id="translate_progress" style="display:none;"><div id="translate_progress1"></div></div></div></form>');
$("#translate_ok").click(GPA.translate.run)},run:function(){GPA.translate.collectCourseNames();var a=$("#translate_form [name=lang]:checked").val();GPA.stat("tools/translate."+a);if(GPA.translate.currentLang!=a)GPA.translate.translation={};GPA.translate.currentLang=a;GPA.translate.resultLocation=$("#translate_form [name=result]:checked").val();$("#translate_ok").attr("disabled",!0);GPA.translate.SJTUTranslator(function(){GPA.translate.renderResult();GPA.translate.BingTranslator(function(){GPA.translate.renderResult();
GPA.popup.close()})})},courseNames:[],collectCourseNames:function(){var a=GPA.translate.courseNames=[];GPA.courses.each(function(b,d){d.name&&$.inArray(d.name,a)<0&&a.push(d.name)})},currentLang:"English",translation:{},getUnknownNames:function(){return $.grep(GPA.translate.courseNames,function(a){return!GPA.translate.translation[a]})},SJTUTranslator:function(a){if(GPA.translate.currentLang!="English")a();else{var b=GPA.translate.getUnknownNames().join("\n");b==""?a():$.post(GPA.server_base+"translate-sjtu.php",
b,function(b){$.extend(GPA.translate.translation,b);a()},"json")}},BingPending:0,BingCount:0,BingCompleted:$.noop,BingTranslator:function(a){var b;switch(GPA.translate.currentLang){case "English":b="En";break;case "French":b="Fr";break;case "German":b="De";break;case "Italian":b="It";break;case "Japanese":b="Ja";break;default:a();return}GPA.translate.BingCompleted=a;var d=GPA.translate.getUnknownNames();d.length==0?a():(GPA.translate.BingCount=d.length,$("#translate_progress").show(),GPA.translate.renderProgress(0),
$.each(d,function(a,d){++GPA.translate.BingPending;W.loadjs("http://api.bing.net/json.aspx?AppId=87365BC18175A2555BFB0BF078223D5B18549986&Query="+encodeURIComponent(d)+"&Sources=Translation&Version=2.2&Market=zh-cn&Translation.SourceLanguage=zh-CHS&Translation.TargetLanguage="+b+"&JsonType=callback&JsonCallback=GPA.translate.BingCallback")}))},BingCallback:function(a){try{GPA.translate.translation[a.SearchResponse.Query.SearchTerms]=a.SearchResponse.Translation.Results[0].TranslatedTerm}catch(b){}var a=
--GPA.translate.BingPending,d=GPA.translate.BingCount;GPA.translate.renderProgress((d-a)/d);a==0&&($("#translate_progress").hide(),GPA.translate.BingCompleted())},renderProgress:function(a){$("#translate_progress1").width(a*400)},resultLocation:"below",renderResult:function(){GPA.courses.each(function(a,b){var d=GPA.translate.translation[b.name];d&&GPA.translate.renderTranslation(a,d)})},renderTranslation:function(a,b){switch(GPA.translate.resultLocation){case "below":$("#C_"+a+"_translation").text(b).length==
0&&$('<span id="C_'+a+'_translation" class="C_translation"></span>').text(b).before("<br>").insertAfter("#C_"+a+"_name");break;case "replace":$("#C_"+a+"_name").val(GPA.courses.get(a).name=b)}}};
GPA.chart={start:function(){GPA.stat("tools/chart");GPA.popup.open("\u7ee9\u70b9\u5206\u5e03\u56fe",'<p><img src="'+GPA.chart.buildChartURI(GPA.chart.collectByPoint())+'" alt="\u7ee9\u70b9\u5206\u5e03\u56fe"></p>')},collectByPoint:function(){var a={};GPA.courses.each(function(b,e){var f=GPA.util.fix1(e.point);a[f]?++a[f]:a[f]=1},!0);var b=[];$.each(a,function(a,e){for(var a=parseFloat(a),f=[a,e],g=0;g<b.length&&b[g][0]<a;)++g;b.splice(g,0,f)});return b},buildChartURI:function(a){var b=[],d=[],e=0;
$.each(a,function(a,g){b.push(g[1]);d.push(g[0]);e=Math.max(e,g[1])});++e;return"http://chart.apis.google.com/chart?chs=480x200&cht=bvs&chd=t:"+b.join(",")+"&chds=0,"+e+"&chxt=x,y&chxl=0:|"+d.join("|")+"&chxr=1,0,"+e+","+Math.floor(e/4)+"&chm=N,000000,0,-1,11"}};
GPA.bygroup={start:function(a){GPA.stat("tools/bygroup?medium="+a);for(var a=GPA.bygroup.collectAllGroups(),b=$('<table id="report_bygroup"><thead><tr><td>\u7ec4\u4ee3\u7801</td><td>\u8bfe\u7a0b\u6570</td><td>\u603b\u5b66\u5206</td><td>GPA</td></thead><tbody></tbody></tr>'),d=b.find("tbody"),e=0;e<a.length;++e){var f=a.charAt(e),g=GPA.bygroup.calcGroup(f),h=$("<tr>");$("<td>").text(f).appendTo(h);$("<td>").text(g.course_count).appendTo(h);$("<td>").text(g.credit_total).appendTo(h);f=g.course_count==
0||g.credit_total==0?"\u2014":isNaN(g.GPA)?"\u00d7":GPA.util.fix4(g.GPA);$("<td>").text(f).appendTo(h);d.append(h)}GPA.popup.open("\u5206\u7ec4\u7edf\u8ba1\u7ed3\u679c",b)},collectAllGroups:function(){var a="";GPA.courses.each(function(b,d){for(var e=0;e<d.groups.length;++e){var f=d.groups.charAt(e);a.indexOf(f)<0&&(a+=f)}});return a},buildFilter:function(a){return function(b,d){return d.selected&&d.groups.indexOf(a)>=0}},calcGroup:function(a){return(new GPA.collector(GPA.bygroup.buildFilter(a))).getResult()},
resultToString:function(a){return a.course_count==0||a.credit_total==0?"\u6ca1\u6709\u9009\u4e2d\u7684\u8bfe\u7a0b":isNaN(a.GPA)?"\u90e8\u5206\u6210\u7ee9\u65e0\u6cd5\u8bc6\u522b\uff0c\u672a\u80fd\u7b97\u51fa\u7ed3\u679c":""+a.course_count+"\u95e8\u8bfe\u7a0b\uff0c\u603b\u5b66\u5206="+a.credit_total+"\uff0cGPA="+GPA.util.fix4(a.GPA)}};
GPA.help={init:function(){GPA.menu.registerAction("help_welcome",GPA.help.showWelcome);GPA.menu.registerAction("help_about",function(){alert("\u9633\u5149GPA\u8ba1\u7b97\u5668\n\u00a92010 yoursunny.com")});GPA.menu.registerAction("help_2009",function(){window.open("/study/GPA/2009/")});$("#loading").html('<input type="button" value="\u6211\u77e5\u9053\u4e86">').find(":button").click(GPA.help.dismissWelcome);GPA.storage.get("welcome")&&$("#welcome").hide()},showWelcome:function(){$("#welcome").slideDown()},
dismissWelcome:function(){GPA.storage.set("welcome",(new Date).getTime(),!0);$("#welcome").slideUp()}};
GPA.util={normalizeFloat:function(a){return(a=(""+a).match(/[0-9]*(?:\.[0-9]*)?/))?a[0].replace(/^\./,"0.").replace(/\.$/,""):""},fix1:function(a){if(isNaN(a))return"NaN";a=""+Math.round(a*10);return a.length==1?"0."+a:a.replace(/([0-9])$/,".$1")},fix4:function(a){if(isNaN(a))return"NaN";a=""+Math.round(a*1E4);if(a.length<=4){for(;a.length<4;)a="0"+a;return"0."+a}else return a.replace(/([0-9]{4})$/,".$1")},reset_hiddenframe:function(){$("#hiddenframe").attr("src","about:blank")},getcsv:function(a,
b){for(var d=[],e=-1,f="",g=!1,h=!1;++e<a.length;){var i=a.charAt(e);if(g)f+=i,g=!1;else switch(i){case b.enclosure:h=!h;break;case b.delimeter:h?f+=i:(d.push(f),f="");break;case b.escape:g=!0;break;default:f+=i}}d.push(f);return d},replace_ok_cancel:function(a){var b=navigator.language?navigator.language:navigator.userLanguage;if(!b)return a;if(/^en/i.test(b))return a.replace(/\u3010\u786e\u5b9a\u3011/g,"\u3010OK\u3011").replace(/\u3010\u53d6\u6d88\u3011/g,"\u3010Cancel\u3011");return a},allLevels:["A",
"A+","A","A-","B","B+","B","B-","C","C+","C","C-","D","D+","D","D-","E","E+","E","E-","P","F"],translateLevelPairs:{"A-":"B+","B+":"A-","B-":"C+","C+":"B-","C-":"D+","D+":"C-"},isLevel:function(a){return $.inArray(a,GPA.util.allLevels)>=0},parseLevelOrGrade:function(a){a=a.toUpperCase();return GPA.util.isLevel(a)?a:GPA.util.normalizeFloat(a)},translateLevel:function(a,b){var d=GPA.util.translateLevelPairs[a];if($.inArray(d,b)>=0)return d;for(d=$.inArray(a,GPA.util.allLevels);d>=0&&$.inArray(GPA.util.allLevels[d],
b)<0;)--d;if(d<0)return"";return GPA.util.allLevels[d]},parseGroups:function(a){for(var b="",d=0;d<a.length;++d){var e=a.charAt(d);b.indexOf(e)<0&&(b+=e)}return b}};
GPA.storage={init:function(){window.localStorage&&localStorage.getItem?GPA.storage.supportLS=!0:($.cookie("testCookie","7f89d7c4-eab4-493a-8daf-536cfd00e96c"),GPA.storage.serverCookie=$.cookie("testCookie")!="7f89d7c4-eab4-493a-8daf-536cfd00e96c")},supportLS:!1,serverCookie:null,get:function(a){if(a=GPA.storage.supportLS?localStorage.getItem("sunnyGPA_"+a):$.cookie(a))try{return $.parseJSON(a)}catch(b){}return null},setJSON:function(a,b,d){if(GPA.storage.supportLS)return localStorage.setItem("sunnyGPA_"+
a,b),!0;else if(d)return GPA.storage.serverCookie?$("#hiddenframe").attr("src",GPA.server_base+"setcookie.php?"+$.param({name:a,value:b})):$.cookie(a,b,{expires:999}),!0;return!1},set:function(a,b,d){var e;try{e=$.toJSON(b)}catch(f){return!1}return GPA.storage.setJSON(a,e,d)}};
GPA.autosave={init:function(){if(GPA.storage.supportLS){var a=GPA.autosave.disabled=!!GPA.storage.get("autosave_disabled");$("#autosave").html('<label><input type="checkbox" id="autosave_enable"'+(a?"":"checked")+'>\u9000\u51fa\u65f6\u81ea\u52a8\u4fdd\u5b58\u8bfe\u7a0b\u4fe1\u606f\u5230\u6d4f\u89c8\u5668\u672c\u5730\u5b58\u50a8</label> <a href="javascript:;" id="autosave_clear">\u6e05\u9664\u5df2\u5b58\u50a8\u4fe1\u606f</a>');$("#autosave_clear").toggle(a).click(function(){GPA.storage.set("coursedata",
null);alert("\u5df2\u7ecf\u6e05\u9664\u672c\u5730\u5b58\u50a8\u4e2d\u7684\u8bfe\u7a0b\u4fe1\u606f")});$("#autosave_enable").click(function(){a=GPA.autosave.disabled=!$("#autosave_enable").is(":checked");$("#autosave_clear").toggle(a);GPA.storage.set("autosave_disabled",a)})}else $("#autosave").html("\u4f60\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u672c\u5730\u5b58\u50a8\uff0c\u9000\u51fa\u524d\u8bf7\u624b\u52a8\u5bfc\u51fa\u8bfe\u7a0b\u4fe1\u606f"),GPA.storage.serverCookie&&$("#algs").bind("GPA_updateRecentAlg",
function(){GPA.storage.set("recentAlg",GPA.alg.recentList.list,!0)});GPA.autosave.onLoad();$(window).unload(GPA.autosave.onUnload)},disabled:!1,onLoad:function(){GPA.alg.recentList.fromStorage(GPA.storage.get("recentAlg"));var a=GPA.storage.get("coursedata");a&&(a=GPA.imp.json.parseJSON(a)[1])&&GPA.calc.importCourses(a,!0)},onUnload:function(){GPA.storage.set("recentAlg",GPA.alg.recentList.list,!0);GPA.autosave.disabled||GPA.storage.setJSON("coursedata",GPA.save.json.getCoursesJSON())}};